import { createContext, useCallback, useContext, useEffect, useState } from 'react';

export const LANGUAGES = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिन्दी' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
  { code: 'ta', label: 'Tamil', nativeLabel: 'தமிழ்' },
];

const translations = {
  hi: {
    Home: 'होम', Crops: 'फसलें', Weather: 'मौसम', Market: 'बाज़ार', Profile: 'प्रोफ़ाइल',
    Settings: 'सेटिंग्स', Notifications: 'सूचनाएं', Logout: 'लॉग आउट',
    'Add Crop': 'फसल जोड़ें', 'Crop Advisor': 'फसल सलाहकार', 'Profit Calc': 'लाभ गणना',
    Irrigation: 'सिंचाई', 'My Profile': 'मेरी प्रोफ़ाइल', 'Market & Demand': 'बाज़ार और मांग',
    'Profit Calculator': 'लाभ कैलकुलेटर', 'Smart Irrigation': 'स्मार्ट सिंचाई',
    'AI Crop Advisor': 'फसल सलाहकार', 'Add New Crop': 'नई फसल जोड़ें',
    'Good morning 🌅': 'सुप्रभात 🌅', 'Quick Actions': 'त्वरित कार्रवाइयां',
    'Active Crops': 'सक्रिय फसलें', 'My Crops': 'मेरी फसलें', 'View All →': 'सभी देखें →',
    'Live Farm Forecast': 'खेत का मौसम पूर्वानुमान',
    'Current conditions and a five-day forecast for your location': 'आपके स्थान का वर्तमान मौसम और पांच दिन का पूर्वानुमान',
    'Find crops for your farm': 'अपने खेत के लिए फसलें चुनें',
    'Recommendations use your soil, water source, and growing season.': 'सुझाव मिट्टी, पानी के स्रोत और मौसम पर आधारित हैं।',
    'Soil type': 'मिट्टी का प्रकार', 'Water availability': 'पानी की उपलब्धता', Season: 'मौसम',
    'Best matches': 'सबसे उपयुक्त', 'Soil match': 'मिट्टी के अनुकूल',
    'Check local soil suitability': 'स्थानीय मिट्टी की उपयुक्तता जांचें',
    'Water match': 'पानी के अनुकूल', 'Plan reliable irrigation': 'सिंचाई की योजना बनाएं',
    'These are general planning suggestions, not a guarantee of yield. Confirm seed choice and planting dates with your local agriculture extension office.': 'ये सामान्य सुझाव हैं, उपज की गारंटी नहीं। बीज और बुवाई की तारीख स्थानीय कृषि कार्यालय से जांचें।',
    'Watering intervals are starting estimates based on crop stage, soil, and water availability. Check soil moisture and local conditions before watering.': 'सिंचाई अंतराल फसल की अवस्था, मिट्टी और पानी के आधार पर अनुमान हैं। पानी देने से पहले मिट्टी की नमी जांचें।',
    'Watering method to log': 'सिंचाई का तरीका', 'Check moisture': 'नमी जांचें',
    'Recently watered': 'हाल ही में पानी दिया', 'Log watering': 'सिंचाई दर्ज करें',
    'No active crops to plan for': 'योजना के लिए सक्रिय फसलें नहीं हैं',
    'Add a crop to get stage-based watering guidance.': 'सिंचाई सुझाव पाने के लिए फसल जोड़ें।',
    'Starting interval: about every ': 'अनुमानित अंतराल: हर ', days: 'दिन',
    'Last watered: ': 'अंतिम सिंचाई: ', 'No watering logged yet': 'अभी तक सिंचाई दर्ज नहीं',
    'City or district': 'शहर या जिला', Search: 'खोजें',
    'Loading local forecast...': 'स्थानीय मौसम लोड हो रहा है...',
    '5-day forecast': '5 दिन का पूर्वानुमान', Humidity: 'नमी', Wind: 'हवा',
    'Precipitation now: ': 'अभी वर्षा: ',
    'Forecast by Open-Meteo. Use local observations for farm decisions.': 'Open-Meteo का पूर्वानुमान। खेती के निर्णय स्थानीय स्थिति देखकर लें।',
    'Crop & Area': 'फसल और क्षेत्र', 'Yield & Price': 'उपज और मूल्य',
    'Cultivation Costs (₹)': 'खेती की लागत (₹)', Crop: 'फसल', 'Land Area': 'भूमि क्षेत्र',
    Unit: 'इकाई', 'Expected Yield per Acre (kg)': 'प्रति एकड़ अनुमानित उपज (किग्रा)',
    'Selling Price per kg (₹)': 'प्रति किग्रा बिक्री मूल्य (₹)', 'Calculate Profit': 'लाभ की गणना करें',
    'Estimated Profit': 'अनुमानित लाभ', 'Total Yield': 'कुल उपज', 'Expected Revenue': 'अनुमानित आय',
    'Total Cost': 'कुल लागत', 'All figures are': 'सभी आंकड़े', estimates: 'अनुमान',
    'based on your inputs. Actual profit may vary.': 'आपकी जानकारी पर आधारित हैं। वास्तविक लाभ अलग हो सकता है।',
    'Select Crop': 'फसल चुनें', 'Crop Details': 'फसल का विवरण', 'Crop Name *': 'फसल का नाम *',
    'Select a crop': 'फसल चुनें', 'Land Area *': 'भूमि क्षेत्र *', 'Dates & Yield': 'तारीख और उपज',
    'Planting Date *': 'बुवाई की तारीख *', 'Expected Harvest Date': 'अनुमानित कटाई की तारीख',
    'Expected Yield': 'अनुमानित उपज', 'Soil & Water': 'मिट्टी और पानी',
    'Water Source': 'पानी का स्रोत', 'Notes (Optional)': 'टिप्पणी (वैकल्पिक)',
    '🌱 Add Crop': '🌱 फसल जोड़ें',
    'English': 'अंग्रेज़ी', 'Hindi': 'हिन्दी', 'Telugu': 'तेलुगु', 'Tamil': 'तमिल',
    'Account & Location': 'खाता और स्थान', 'Personal information and farm location': 'व्यक्तिगत जानकारी और खेत का स्थान',
    'Full name': 'पूरा नाम', Email: 'ईमेल', 'Phone number': 'फ़ोन नंबर',
    Village: 'गांव', District: 'जिला', State: 'राज्य', Language: 'भाषा',
    'Choose the language used across AgroSelf.': 'AgroSelf में उपयोग की जाने वाली भाषा चुनें।',
    'Save settings': 'सेटिंग्स सहेजें', 'Settings saved successfully.': 'सेटिंग्स सफलतापूर्वक सहेजी गईं।',
    'Could not save settings. Please try again.': 'सेटिंग्स सहेजी नहीं जा सकीं। फिर कोशिश करें।',
    'Account details': 'खाते का विवरण', 'Farm location': 'खेत का स्थान',
    'Go back': 'वापस जाएं', 'Registration failed. Please try again.': 'पंजीकरण विफल हुआ। फिर कोशिश करें।',
    'Login failed. Please try again.': 'लॉगिन विफल हुआ। फिर कोशिश करें।',
    'Dashboard': 'डैशबोर्ड', 'Hello, ': 'नमस्ते, ', 'Your Farm': 'आपका खेत',
    'No active crops yet': 'अभी कोई सक्रिय फसल नहीं', 'Add your first crop to start tracking': 'ट्रैकिंग शुरू करने के लिए पहली फसल जोड़ें',
    '+ Add First Crop': '+ पहली फसल जोड़ें', 'Today\'s Weather': 'आज का मौसम', 'Details →': 'विवरण →',
    'Expected:': 'अनुमानित:', 'View →': 'देखें →', Harvest: 'कटाई',
    'No data available': 'कोई डेटा उपलब्ध नहीं', 'All Demand': 'सभी मांग', 'High Demand': 'उच्च मांग',
    'Medium Demand': 'मध्यम मांग', 'Low Demand': 'कम मांग', 'Loading market data...': 'बाज़ार डेटा लोड हो रहा है...',
    '🌱 Seed Cost': '🌱 बीज लागत', '🧪 Fertilizer Cost': '🧪 खाद लागत', '👷 Labour Cost': '👷 मजदूरी',
    '💧 Irrigation Cost': '💧 सिंचाई लागत', '🧴 Pesticide Cost': '🧴 कीटनाशक लागत', '📦 Other Costs': '📦 अन्य लागत',
    'Profit Estimate': 'लाभ अनुमान', 'ESTIMATED PROFIT': 'अनुमानित लाभ', 'per acre': 'प्रति एकड़', margin: 'लाभ मार्जिन',
    'Weather unavailable': 'मौसम उपलब्ध नहीं', 'Clear sky': 'साफ़ आसमान', 'Partly cloudy': 'आंशिक बादल',
    Fog: 'कोहरा', Drizzle: 'बूंदाबांदी', Rain: 'बारिश', Snow: 'बर्फ़बारी', Thunderstorm: 'आंधी-तूफ़ान',
    'Conditions unavailable': 'मौसम की जानकारी उपलब्ध नहीं', 'Feels like': 'महसूस हो रहा है', Updated: 'अपडेट',
    'No matching location found for': 'इस स्थान के लिए जानकारी नहीं मिली:',
    'Enter a city or district to get a forecast.': 'पूर्वानुमान के लिए शहर या जिला दर्ज करें।',
    'Location search is unavailable. Please try again.': 'स्थान खोज उपलब्ध नहीं है। फिर कोशिश करें।',
    'Weather forecast is unavailable. Please try again shortly.': 'मौसम पूर्वानुमान उपलब्ध नहीं है। थोड़ी देर बाद कोशिश करें।',
    'Could not load weather. Check your connection and try again.': 'मौसम लोड नहीं हुआ। इंटरनेट जांचकर फिर कोशिश करें।',
    'Personal Details': 'व्यक्तिगत जानकारी', 'Farm Location': 'खेत का स्थान', 'Land Details': 'भूमि विवरण',
    'Continue →': 'जारी रखें →', '← Back': '← वापस', 'Create Account': 'खाता बनाएं',
    'Login to AgroSelf': 'AgroSelf में लॉगिन करें', 'Welcome Back 👋': 'वापसी पर स्वागत है 👋',
    'Login to manage your farm': 'अपने खेत का प्रबंधन करने के लिए लॉगिन करें', 'Email Address': 'ईमेल पता',
    Password: 'पासवर्ड', 'New farmer?': 'नए किसान हैं?', 'Create New Account': 'नया खाता बनाएं',
    'Full Name *': 'पूरा नाम *', 'Phone Number *': 'फ़ोन नंबर *', 'Password *': 'पासवर्ड *',
    'Village / Town': 'गांव / कस्बा', 'District *': 'जिला *', 'State *': 'राज्य *',
    'Select your state': 'अपना राज्य चुनें',
    'Soil Type': 'मिट्टी का प्रकार', 'Water Availability': 'पानी की उपलब्धता', 'Irrigation Type': 'सिंचाई का प्रकार',
    'Select State': 'राज्य चुनें', 'Saving...': 'सहेजा जा रहा है...', 'You are offline': 'आप ऑफ़लाइन हैं', Offline: 'ऑफ़लाइन',
    'The selected language is saved on this device.': 'चुनी गई भाषा इस डिवाइस पर सहेजी जाती है।',
    'Save Changes': 'बदलाव सहेजें', Cancel: 'रद्द करें', 'Edit Profile': 'प्रोफ़ाइल संपादित करें',
    'Profile updated successfully!': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हुई!', 'Update failed.': 'अपडेट विफल हुआ।',
    'No notifications yet': 'अभी कोई सूचना नहीं', 'Clear Read': 'पढ़ी गई हटाएं', Loading: 'लोड हो रहा है...',
    'unread': 'अपठित', 'Failed to load notifications.': 'सूचनाएं लोड नहीं हो सकीं।',
    'Failed to add crop. Please try again.': 'फसल नहीं जुड़ी। फिर कोशिश करें।',
    'Please select or enter a crop name.': 'फसल चुनें या उसका नाम लिखें।',
    'Please enter land area.': 'भूमि क्षेत्र दर्ज करें।', 'Please enter planting date.': 'बुवाई की तारीख दर्ज करें।',
    'Red Sandy': 'लाल रेतीली', 'Black Cotton': 'काली कपासी', 'Loamy': 'दोमट',
    'Sandy Loam': 'रेतीली दोमट', Clay: 'चिकनी मिट्टी', Alluvial: 'जलोढ़', Laterite: 'लैटेराइट',
    Borewell: 'बोरवेल', Canal: 'नहर', 'Rain-fed': 'वर्षा आधारित', River: 'नदी', Pond: 'तालाब', Limited: 'सीमित',
    Planting: 'बुवाई', Seedling: 'अंकुर', Vegetative: 'विकास', Flowering: 'फूल आना',
    'Fruit Development': 'फल विकास',
    Chilli: 'मिर्च', Tomato: 'टमाटर', Brinjal: 'बैंगन', Groundnut: 'मूंगफली', Cotton: 'कपास',
    Maize: 'मक्का', Rice: 'धान', Wheat: 'गेहूं', Onion: 'प्याज', Potato: 'आलू', Turmeric: 'हल्दी',
    Sugarcane: 'गन्ना', Sunflower: 'सूरजमुखी', Soybean: 'सोयाबीन', 'Moong Dal': 'मूंग दाल',
    Okra: 'भिंडी', Cucumber: 'खीरा', Watermelon: 'तरबूज', 'Bitter Gourd': 'करेला', Coriander: 'धनिया',
    acres: 'एकड़', hectares: 'हेक्टेयर', guntas: 'गुंटा', kg: 'किग्रा', tonnes: 'टन', quintals: 'क्विंटल',
    'Land & Soil': 'भूमि और मिट्टी',
    'Tell us about yourself': 'अपने बारे में बताएं', 'Where is your farm located?': 'आपका खेत कहां स्थित है?',
    'Tell us about your farmland': 'अपने खेत के बारे में बताएं', 'Full Name': 'पूरा नाम', 'Phone Number': 'फ़ोन नंबर',
    'Min. 6 characters': 'कम से कम 6 अक्षर', 'Enter a valid 10-digit phone number.': '10 अंकों का सही फ़ोन नंबर दर्ज करें।',
    'Enter a valid email address.': 'सही ईमेल पता दर्ज करें।', 'Password must be at least 6 characters.': 'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
    'Please enter your name.': 'अपना नाम दर्ज करें।', 'Please enter your district.': 'अपना जिला दर्ज करें।',
    'Please select your state.': 'अपना राज्य चुनें।', 'Already have an account?': 'क्या आपका पहले से खाता है?',
    'Login here': 'यहां लॉगिन करें', 'Creating...': 'खाता बनाया जा रहा है...', 'Create Account ✓': 'खाता बनाएं ✓',
    'e.g. Ramesh Kumar': 'उदा. रमेश कुमार', 'e.g. 9876543210': 'उदा. 9876543210',
    'e.g. Kothapalli': 'उदा. कोठापल्ली', 'e.g. Guntur': 'उदा. गुंटूर',
    'e.g. 3': 'उदा. 3', 'e.g. 1500': 'उदा. 1500',
    'No crops added yet': 'अभी कोई फसल नहीं जोड़ी गई', 'Start by adding your first crop': 'पहली फसल जोड़कर शुरुआत करें',
    'Harvested': 'कटाई हुई', 'Expected Harvest:': 'अनुमानित कटाई:',
    'Loading crops...': 'फसलें लोड हो रही हैं...', 'Planted': 'बुवाई हुई', 'active crop': 'सक्रिय फसल', 'active crops': 'सक्रिय फसलें',
    'Growth Stage': 'विकास अवस्था', 'Updating...': 'अपडेट हो रहा है...', 'Advance to': 'आगे बढ़ें:',
    'This crop has reached the Harvest stage!': 'यह फसल कटाई की अवस्था में पहुंच गई है!',
    Watering: 'सिंचाई', 'Last watered:': 'अंतिम सिंचाई:', 'Not recorded': 'दर्ज नहीं है',
    'Log Watering': 'सिंचाई दर्ज करें', 'Crop Info': 'फसल की जानकारी', 'Planted On': 'बुवाई की तारीख',
    Edit: 'संपादित करें', 'days away': 'दिन बाकी', 'Ready to harvest!': 'कटाई के लिए तैयार!',
    'Delete Crop': 'फसल हटाएं', 'Are you sure you want to delete': 'क्या आप इसे हटाना चाहते हैं:',
    'Yes, Delete': 'हां, हटाएं', 'Date & Time': 'तारीख और समय', Method: 'तरीका', Notes: 'टिप्पणियां',
    'Optional notes...': 'वैकल्पिक टिप्पणी...', '💧 Save': '💧 सहेजें',
    'Phone': 'फ़ोन', Contact: 'संपर्क', Location: 'स्थान', 'Total Area': 'कुल क्षेत्र',
    'Failed to load market data.': 'बाज़ार डेटा लोड नहीं हुआ।', Note: 'ध्यान दें',
    'Prices shown are indicative estimates from APMC markets. Real market data integration planned for a future phase.': 'दिखाई गई कीमतें APMC बाजारों के संकेतात्मक अनुमान हैं।',
    'Join AgroSelf': 'AgroSelf से जुड़ें', 'Create your free farmer account': 'अपना निःशुल्क किसान खाता बनाएं',
    'Smart Farming for Every Farmer': 'हर किसान के लिए स्मार्ट खेती', 'Email Address *': 'ईमेल पता *',
    'ramesh@example.com': 'ramesh@example.com', 'Toggle password visibility': 'पासवर्ड दिखाएं या छिपाएं',
    'Crop Name (Custom) *': 'फसल का नाम (अन्य) *', 'Enter crop name': 'फसल का नाम दर्ज करें',
    'Any additional notes about this crop...': 'इस फसल के बारे में अतिरिक्त जानकारी...', 'Adding Crop...': 'फसल जोड़ी जा रही है...',
    'Could not save watering log. Please try again.': 'सिंचाई दर्ज नहीं हुई। फिर कोशिश करें।',
    'Watering logged for': 'सिंचाई दर्ज हुई:', 'day': 'दिन', rain: 'बारिश',
    'is ready to harvest!': 'कटाई के लिए तैयार है!', 'harvest in': 'कटाई में', 'more crops': 'और फसलें',
    'This is an estimate only. Market prices and actual yield may vary.': 'यह केवल अनुमान है। बाज़ार मूल्य और वास्तविक उपज बदल सकते हैं।',
    'Rain alerts, watering reminders, and harvest notifications will appear here.': 'बारिश अलर्ट, सिंचाई और कटाई की सूचनाएं यहां दिखेंगी।',
    'Crop not found or access denied.': 'फसल नहीं मिली या पहुंच अस्वीकृत है।', 'Loading crop...': 'फसल लोड हो रही है...',
    'Expected Harvest': 'अनुमानित कटाई',
    'Andhra Pradesh': 'आंध्र प्रदेश', Telangana: 'तेलंगाना', Karnataka: 'कर्नाटक', Maharashtra: 'महाराष्ट्र',
    'Tamil Nadu': 'तमिलनाडु', Kerala: 'केरल', Gujarat: 'गुजरात', Rajasthan: 'राजस्थान', 'Uttar Pradesh': 'उत्तर प्रदेश',
    'Arunachal Pradesh': 'अरुणाचल प्रदेश', Assam: 'असम', Bihar: 'बिहार', Chhattisgarh: 'छत्तीसगढ़', Goa: 'गोवा', Haryana: 'हरियाणा',
    'Himachal Pradesh': 'हिमाचल प्रदेश', Jharkhand: 'झारखंड', 'Madhya Pradesh': 'मध्य प्रदेश', Manipur: 'मणिपुर', Meghalaya: 'मेघालय',
    Mizoram: 'मिज़ोरम', Nagaland: 'नागालैंड', Odisha: 'ओडिशा', Punjab: 'पंजाब', Sikkim: 'सिक्किम', Tripura: 'त्रिपुरा',
    Uttarakhand: 'उत्तराखंड', 'West Bengal': 'पश्चिम बंगाल', Kharif: 'खरीफ़', Rabi: 'रबी', Zaid: 'ज़ायद', 'Year-round': 'पूरे वर्ष', Other: 'अन्य',
    Drip: 'ड्रिप', Sprinkler: 'स्प्रिंकलर', Flood: 'बाढ़ सिंचाई', Manual: 'मैनुअल', None: 'कोई नहीं',
    High: 'उच्च', Medium: 'मध्यम', Low: 'कम', Rising: 'बढ़ता हुआ', Stable: 'स्थिर', Falling: 'गिरता हुआ',
  },
  te: {
    Home: 'హోమ్', Crops: 'పంటలు', Weather: 'వాతావరణం', Market: 'మార్కెట్', Profile: 'ప్రొఫైల్',
    Settings: 'సెట్టింగ్‌లు', Notifications: 'నోటిఫికేషన్‌లు', Logout: 'లాగ్ అవుట్',
    'Add Crop': 'పంటను జోడించండి', 'Crop Advisor': 'పంట సలహాదారు', 'Profit Calc': 'లాభం లెక్కింపు',
    Irrigation: 'నీటిపారుదల', 'My Profile': 'నా ప్రొఫైల్', 'Market & Demand': 'మార్కెట్ మరియు డిమాండ్',
    'Profit Calculator': 'లాభ కాలిక్యులేటర్', 'Smart Irrigation': 'స్మార్ట్ నీటిపారుదల',
    'AI Crop Advisor': 'పంట సలహాదారు', 'Add New Crop': 'కొత్త పంటను జోడించండి',
    'Good morning 🌅': 'శుభోదయం 🌅', 'Quick Actions': 'త్వరిత చర్యలు',
    'Active Crops': 'ప్రస్తుత పంటలు', 'My Crops': 'నా పంటలు', 'View All →': 'అన్నీ చూడండి →',
    'Live Farm Forecast': 'వ్యవసాయ వాతావరణ సూచన',
    'Current conditions and a five-day forecast for your location': 'మీ ప్రాంతానికి ప్రస్తుత పరిస్థితులు మరియు ఐదు రోజుల సూచన',
    'Find crops for your farm': 'మీ పొలానికి తగిన పంటలు',
    'Recommendations use your soil, water source, and growing season.': 'మీ నేల, నీటి వనరు, పంటకాలం ఆధారంగా సూచనలు.',
    'Soil type': 'నేల రకం', 'Water availability': 'నీటి లభ్యత', Season: 'పంట కాలం',
    'Best matches': 'మంచి ఎంపికలు', 'Soil match': 'నేలకు అనుకూలం',
    'Check local soil suitability': 'స్థానిక నేలకు సరిపోతుందో చూడండి',
    'Water match': 'నీటికి అనుకూలం', 'Plan reliable irrigation': 'నీటిపారుదల ప్రణాళిక చేయండి',
    'These are general planning suggestions, not a guarantee of yield. Confirm seed choice and planting dates with your local agriculture extension office.': 'ఇవి సాధారణ సూచనలు మాత్రమే; దిగుబడికి హామీ కాదు. విత్తనాలు, విత్తే తేదీలను స్థానిక వ్యవసాయ కార్యాలయంలో నిర్ధారించండి.',
    'Watering intervals are starting estimates based on crop stage, soil, and water availability. Check soil moisture and local conditions before watering.': 'పంట దశ, నేల, నీటి లభ్యత ఆధారంగా ఇవి ప్రాథమిక అంచనాలు. నీరు పెట్టే ముందు నేల తేమను పరిశీలించండి.',
    'Watering method to log': 'నమోదు చేసే నీటిపారుదల విధానం', 'Check moisture': 'తేమను పరిశీలించండి',
    'Recently watered': 'ఇటీవల నీరు పెట్టారు', 'Log watering': 'నీటిపారుదలను నమోదు చేయండి',
    'No active crops to plan for': 'ప్రణాళికకు ప్రస్తుత పంటలు లేవు',
    'Add a crop to get stage-based watering guidance.': 'దశల వారీ నీటిపారుదల సూచనల కోసం పంటను జోడించండి.',
    'Starting interval: about every ': 'ప్రాథమిక వ్యవధి: ప్రతి ', days: 'రోజులకు',
    'Last watered: ': 'చివరిగా నీరు పెట్టిన సమయం: ', 'No watering logged yet': 'ఇంకా నీటిపారుదల నమోదు కాలేదు',
    'City or district': 'నగరం లేదా జిల్లా', Search: 'వెతకండి',
    'Loading local forecast...': 'స్థానిక వాతావరణం లోడ్ అవుతోంది...',
    '5-day forecast': '5 రోజుల వాతావరణ సూచన', Humidity: 'తేమ', Wind: 'గాలి',
    'Precipitation now: ': 'ప్రస్తుత వర్షపాతం: ',
    'Forecast by Open-Meteo. Use local observations for farm decisions.': 'Open-Meteo సూచన. వ్యవసాయ నిర్ణయాలకు స్థానిక పరిస్థితులను గమనించండి.',
    'Crop & Area': 'పంట మరియు విస్తీర్ణం', 'Yield & Price': 'దిగుబడి మరియు ధర',
    'Cultivation Costs (₹)': 'సాగు ఖర్చులు (₹)', Crop: 'పంట', 'Land Area': 'భూమి విస్తీర్ణం',
    Unit: 'యూనిట్', 'Expected Yield per Acre (kg)': 'ఎకరానికి అంచనా దిగుబడి (కిలోలు)',
    'Selling Price per kg (₹)': 'కిలోకు అమ్మకపు ధర (₹)', 'Calculate Profit': 'లాభాన్ని లెక్కించండి',
    'Estimated Profit': 'అంచనా లాభం', 'Total Yield': 'మొత్తం దిగుబడి', 'Expected Revenue': 'అంచనా ఆదాయం',
    'Total Cost': 'మొత్తం ఖర్చు', 'All figures are': 'అన్ని గణాంకాలు', estimates: 'అంచనాలు',
    'based on your inputs. Actual profit may vary.': 'మీరు ఇచ్చిన వివరాల ఆధారంగా ఉంటాయి. నిజమైన లాభం మారవచ్చు.',
    'Select Crop': 'పంటను ఎంచుకోండి', 'Crop Details': 'పంట వివరాలు', 'Crop Name *': 'పంట పేరు *',
    'Select a crop': 'పంటను ఎంచుకోండి', 'Land Area *': 'భూమి విస్తీర్ణం *', 'Dates & Yield': 'తేదీలు మరియు దిగుబడి',
    'Planting Date *': 'విత్తిన తేదీ *', 'Expected Harvest Date': 'అంచనా కోత తేదీ',
    'Expected Yield': 'అంచనా దిగుబడి', 'Soil & Water': 'నేల మరియు నీరు',
    'Water Source': 'నీటి వనరు', 'Notes (Optional)': 'గమనికలు (ఐచ్ఛికం)',
    '🌱 Add Crop': '🌱 పంటను జోడించండి',
    English: 'ఆంగ్లం', Hindi: 'హిందీ', Telugu: 'తెలుగు', Tamil: 'తమిళం',
    'Account & Location': 'ఖాతా మరియు ప్రాంతం', 'Personal information and farm location': 'వ్యక్తిగత సమాచారం మరియు పొలం ప్రాంతం',
    'Full name': 'పూర్తి పేరు', Email: 'ఇమెయిల్', 'Phone number': 'ఫోన్ నంబర్',
    Village: 'గ్రామం', District: 'జిల్లా', State: 'రాష్ట్రం', Language: 'భాష',
    'Choose the language used across AgroSelf.': 'AgroSelf అంతటా ఉపయోగించే భాషను ఎంచుకోండి.',
    'Save settings': 'సెట్టింగ్‌లను భద్రపరచండి', 'Settings saved successfully.': 'సెట్టింగ్‌లు విజయవంతంగా భద్రపరచబడ్డాయి.',
    'Could not save settings. Please try again.': 'సెట్టింగ్‌లను భద్రపరచలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
    'Account details': 'ఖాతా వివరాలు', 'Farm location': 'పొలం ప్రాంతం',
    'Go back': 'వెనక్కి వెళ్లండి', 'Registration failed. Please try again.': 'నమోదు విఫలమైంది. మళ్లీ ప్రయత్నించండి.',
    'Login failed. Please try again.': 'లాగిన్ విఫలమైంది. మళ్లీ ప్రయత్నించండి.',
    Dashboard: 'డాష్‌బోర్డ్', 'Hello, ': 'నమస్కారం, ', 'Your Farm': 'మీ పొలం',
    'No active crops yet': 'ఇంకా ప్రస్తుత పంటలు లేవు', 'Add your first crop to start tracking': 'ట్రాకింగ్ ప్రారంభించడానికి మొదటి పంటను జోడించండి',
    '+ Add First Crop': '+ మొదటి పంటను జోడించండి', 'Today\'s Weather': 'నేటి వాతావరణం', 'Details →': 'వివరాలు →',
    'Expected:': 'అంచనా:', 'View →': 'చూడండి →', Harvest: 'కోత',
    'No data available': 'డేటా అందుబాటులో లేదు', 'All Demand': 'మొత్తం డిమాండ్', 'High Demand': 'అధిక డిమాండ్',
    'Medium Demand': 'మధ్యస్థ డిమాండ్', 'Low Demand': 'తక్కువ డిమాండ్', 'Loading market data...': 'మార్కెట్ డేటా లోడ్ అవుతోంది...',
    '🌱 Seed Cost': '🌱 విత్తనాల ఖర్చు', '🧪 Fertilizer Cost': '🧪 ఎరువుల ఖర్చు', '👷 Labour Cost': '👷 కూలీ ఖర్చు',
    '💧 Irrigation Cost': '💧 నీటిపారుదల ఖర్చు', '🧴 Pesticide Cost': '🧴 పురుగుమందుల ఖర్చు', '📦 Other Costs': '📦 ఇతర ఖర్చులు',
    'Profit Estimate': 'లాభ అంచనా', 'ESTIMATED PROFIT': 'అంచనా లాభం', 'per acre': 'ఎకరానికి', margin: 'లాభ మార్జిన్',
    'Clear sky': 'ఆకాశం నిర్మలంగా ఉంది', 'Partly cloudy': 'కొంత మేఘావృతం', Fog: 'పొగమంచు',
    Drizzle: 'జల్లులు', Rain: 'వర్షం', Snow: 'మంచు', Thunderstorm: 'ఉరుములతో కూడిన వర్షం',
    'Conditions unavailable': 'వాతావరణ సమాచారం లేదు', 'Feels like': 'అనుభూతి', Updated: 'నవీకరించబడింది',
    'No matching location found for': 'ఈ ప్రాంతం కనబడలేదు:',
    'Enter a city or district to get a forecast.': 'వాతావరణ సూచన కోసం నగరం లేదా జిల్లాను నమోదు చేయండి.',
    'Location search is unavailable. Please try again.': 'ప్రాంత శోధన అందుబాటులో లేదు. మళ్లీ ప్రయత్నించండి.',
    'Weather forecast is unavailable. Please try again shortly.': 'వాతావరణ సూచన అందుబాటులో లేదు. కొద్దిసేపటి తర్వాత ప్రయత్నించండి.',
    'Could not load weather. Check your connection and try again.': 'వాతావరణాన్ని లోడ్ చేయలేకపోయాం. కనెక్షన్ తనిఖీ చేసి మళ్లీ ప్రయత్నించండి.',
    'Personal Details': 'వ్యక్తిగత వివరాలు', 'Farm Location': 'పొలం ప్రాంతం', 'Land Details': 'భూమి వివరాలు',
    'Continue →': 'కొనసాగించండి →', '← Back': '← వెనక్కి', 'Create Account': 'ఖాతా సృష్టించండి',
    'Login to AgroSelf': 'AgroSelf లోకి లాగిన్ అవ్వండి', 'Welcome Back 👋': 'తిరిగి స్వాగతం 👋',
    'Login to manage your farm': 'మీ పొలాన్ని నిర్వహించడానికి లాగిన్ అవ్వండి', 'Email Address': 'ఇమెయిల్ చిరునామా',
    Password: 'పాస్‌వర్డ్', 'New farmer?': 'కొత్త రైతా?', 'Create New Account': 'కొత్త ఖాతా సృష్టించండి',
    'Full Name *': 'పూర్తి పేరు *', 'Phone Number *': 'ఫోన్ నంబర్ *', 'Password *': 'పాస్‌వర్డ్ *',
    'Village / Town': 'గ్రామం / పట్టణం', 'District *': 'జిల్లా *', 'State *': 'రాష్ట్రం *',
    'Select your state': 'మీ రాష్ట్రాన్ని ఎంచుకోండి',
    'Soil Type': 'నేల రకం', 'Water Availability': 'నీటి లభ్యత', 'Irrigation Type': 'నీటిపారుదల విధానం',
    'Select State': 'రాష్ట్రాన్ని ఎంచుకోండి', 'Saving...': 'భద్రపరుస్తోంది...', 'You are offline': 'మీరు ఆఫ్‌లైన్‌లో ఉన్నారు', Offline: 'ఆఫ్‌లైన్',
    'Save Changes': 'మార్పులను భద్రపరచండి', Cancel: 'రద్దు', 'Edit Profile': 'ప్రొఫైల్ మార్చండి',
    'Profile updated successfully!': 'ప్రొఫైల్ విజయవంతంగా నవీకరించబడింది!', 'Update failed.': 'నవీకరణ విఫలమైంది.',
    'No notifications yet': 'ఇంకా నోటిఫికేషన్‌లు లేవు', 'Clear Read': 'చదివినవాటిని తొలగించండి', Loading: 'లోడ్ అవుతోంది...',
    unread: 'చదవనివి', 'Failed to load notifications.': 'నోటిఫికేషన్‌లను లోడ్ చేయలేకపోయాం.',
    'Failed to add crop. Please try again.': 'పంటను జోడించలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
    'Please select or enter a crop name.': 'పంటను ఎంచుకోండి లేదా పేరు నమోదు చేయండి.',
    'Please enter land area.': 'భూమి విస్తీర్ణాన్ని నమోదు చేయండి.', 'Please enter planting date.': 'విత్తిన తేదీని నమోదు చేయండి.',
    'Red Sandy': 'ఎర్ర ఇసుక నేల', 'Black Cotton': 'నల్ల రేగడి నేల', Loamy: 'లోమీ నేల',
    'Sandy Loam': 'ఇసుక లోమీ నేల', Clay: 'బంకమట్టి', Alluvial: 'ఒండ్రు నేల', Laterite: 'లేటరైట్ నేల',
    Borewell: 'బోరుబావి', Canal: 'కాలువ', 'Rain-fed': 'వర్షాధారం', River: 'నది', Pond: 'చెరువు', Limited: 'పరిమితం',
    Planting: 'విత్తడం', Seedling: 'మొలక దశ', Vegetative: 'ఆకు దశ', Flowering: 'పూత దశ',
    'Fruit Development': 'కాయ అభివృద్ధి',
    Chilli: 'మిరప', Tomato: 'టమాటా', Brinjal: 'వంకాయ', Groundnut: 'వేరుశెనగ', Cotton: 'పత్తి',
    Maize: 'మొక్కజొన్న', Rice: 'వరి', Wheat: 'గోధుమ', Onion: 'ఉల్లిపాయ', Potato: 'బంగాళాదుంప', Turmeric: 'పసుపు',
    Sugarcane: 'చెరకు', Sunflower: 'పొద్దుతిరుగుడు', Soybean: 'సోయాబీన్', 'Moong Dal': 'పెసరపప్పు',
    Okra: 'బెండకాయ', Cucumber: 'దోసకాయ', Watermelon: 'పుచ్చకాయ', 'Bitter Gourd': 'కాకరకాయ', Coriander: 'కొత్తిమీర',
    acres: 'ఎకరాలు', hectares: 'హెక్టార్లు', guntas: 'గుంటలు', kg: 'కిలోలు', tonnes: 'టన్నులు', quintals: 'క్వింటాళ్లు',
    'Land & Soil': 'భూమి మరియు నేల',
    'Tell us about yourself': 'మీ గురించి చెప్పండి', 'Where is your farm located?': 'మీ పొలం ఎక్కడ ఉంది?',
    'Tell us about your farmland': 'మీ వ్యవసాయ భూమి గురించి చెప్పండి', 'Full Name': 'పూర్తి పేరు', 'Phone Number': 'ఫోన్ నంబర్',
    'Min. 6 characters': 'కనీసం 6 అక్షరాలు', 'Enter a valid 10-digit phone number.': 'సరైన 10 అంకెల ఫోన్ నంబర్ ఇవ్వండి.',
    'Enter a valid email address.': 'సరైన ఇమెయిల్ చిరునామా ఇవ్వండి.', 'Password must be at least 6 characters.': 'పాస్‌వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.',
    'Please enter your name.': 'మీ పేరు నమోదు చేయండి.', 'Please enter your district.': 'మీ జిల్లాను నమోదు చేయండి.',
    'Please select your state.': 'మీ రాష్ట్రాన్ని ఎంచుకోండి.', 'Already have an account?': 'ఇప్పటికే ఖాతా ఉందా?',
    'Login here': 'ఇక్కడ లాగిన్ అవ్వండి', 'Creating...': 'ఖాతా సృష్టిస్తోంది...', 'Create Account ✓': 'ఖాతా సృష్టించండి ✓',
    'e.g. Ramesh Kumar': 'ఉదా. రమేష్ కుమార్', 'e.g. 9876543210': 'ఉదా. 9876543210',
    'e.g. Kothapalli': 'ఉదా. కొత్తపల్లి', 'e.g. Guntur': 'ఉదా. గుంటూరు',
    'e.g. 3': 'ఉదా. 3', 'e.g. 1500': 'ఉదా. 1500',
    'No crops added yet': 'ఇంకా పంటలు జోడించలేదు', 'Start by adding your first crop': 'మొదటి పంటను జోడించి ప్రారంభించండి',
    'Harvested': 'కోత పూర్తయింది', 'Expected Harvest:': 'అంచనా కోత:', 'Loading crops...': 'పంటలు లోడ్ అవుతున్నాయి...', 'Planted': 'నాటినది',
    'active crop': 'ప్రస్తుత పంట', 'active crops': 'ప్రస్తుత పంటలు', 'Growth Stage': 'పంట దశ',
    'Updating...': 'నవీకరిస్తోంది...', 'Advance to': 'తదుపరి దశ:',
    'This crop has reached the Harvest stage!': 'ఈ పంట కోత దశకు చేరుకుంది!',
    Watering: 'నీటిపారుదల', 'Last watered:': 'చివరిగా నీరు పెట్టినది:', 'Not recorded': 'నమోదు కాలేదు',
    'Log Watering': 'నీటిపారుదలను నమోదు చేయండి', 'Crop Info': 'పంట వివరాలు', 'Planted On': 'నాటిన తేదీ',
    Edit: 'మార్చండి', 'days away': 'రోజులు ఉన్నాయి', 'Ready to harvest!': 'కోతకు సిద్ధంగా ఉంది!',
    'Delete Crop': 'పంటను తొలగించండి', 'Are you sure you want to delete': 'తొలగించాలనుకుంటున్నారా:',
    'Yes, Delete': 'అవును, తొలగించు', 'Date & Time': 'తేదీ మరియు సమయం', Method: 'విధానం', Notes: 'గమనికలు',
    'Optional notes...': 'ఐచ్ఛిక గమనికలు...', '💧 Save': '💧 భద్రపరచండి',
    Phone: 'ఫోన్', Contact: 'సంప్రదింపు', Location: 'ప్రాంతం', 'Total Area': 'మొత్తం విస్తీర్ణం',
    'Failed to load market data.': 'మార్కెట్ డేటాను లోడ్ చేయలేకపోయాం.', Note: 'గమనిక',
    'Prices shown are indicative estimates from APMC markets. Real market data integration planned for a future phase.': 'చూపిన ధరలు APMC మార్కెట్ల అంచనాలు మాత్రమే.',
    'Join AgroSelf': 'AgroSelf లో చేరండి', 'Create your free farmer account': 'ఉచిత రైతు ఖాతాను సృష్టించండి',
    'Smart Farming for Every Farmer': 'ప్రతి రైతుకు స్మార్ట్ వ్యవసాయం', 'Email Address *': 'ఇమెయిల్ చిరునామా *',
    'ramesh@example.com': 'ramesh@example.com', 'Toggle password visibility': 'పాస్‌వర్డ్ చూపించు లేదా దాచు',
    'Crop Name (Custom) *': 'పంట పేరు (ఇతర) *', 'Enter crop name': 'పంట పేరును నమోదు చేయండి',
    'Any additional notes about this crop...': 'ఈ పంట గురించి అదనపు గమనికలు...', 'Adding Crop...': 'పంటను జోడిస్తోంది...',
    'Could not save watering log. Please try again.': 'నీటిపారుదలను నమోదు చేయలేకపోయాం. మళ్లీ ప్రయత్నించండి.',
    'Watering logged for': 'నీటిపారుదల నమోదైంది:', day: 'రోజు', rain: 'వర్షం',
    'is ready to harvest!': 'కోతకు సిద్ధంగా ఉంది!', 'harvest in': 'కోతకు మిగిలింది', 'more crops': 'మరిన్ని పంటలు',
    'This is an estimate only. Market prices and actual yield may vary.': 'ఇది అంచనా మాత్రమే. మార్కెట్ ధరలు, నిజమైన దిగుబడి మారవచ్చు.',
    'Rain alerts, watering reminders, and harvest notifications will appear here.': 'వర్ష హెచ్చరికలు, నీటిపారుదల మరియు కోత రిమైండర్లు ఇక్కడ కనిపిస్తాయి.',
    'Crop not found or access denied.': 'పంట కనబడలేదు లేదా అనుమతి లేదు.', 'Loading crop...': 'పంట లోడ్ అవుతోంది...',
    'Expected Harvest': 'అంచనా కోత',
    'Andhra Pradesh': 'ఆంధ్రప్రదేశ్', Telangana: 'తెలంగాణ', Karnataka: 'కర్ణాటక', Maharashtra: 'మహారాష్ట్ర',
    'Tamil Nadu': 'తమిళనాడు', Kerala: 'కేరళ', Gujarat: 'గుజరాత్', Rajasthan: 'రాజస్థాన్', 'Uttar Pradesh': 'ఉత్తరప్రదేశ్',
    'Arunachal Pradesh': 'అరుణాచల్ ప్రదేశ్', Assam: 'అస్సాం', Bihar: 'బీహార్', Chhattisgarh: 'ఛత్తీస్‌గఢ్', Goa: 'గోవా', Haryana: 'హర్యానా',
    'Himachal Pradesh': 'హిమాచల్ ప్రదేశ్', Jharkhand: 'జార్ఖండ్', 'Madhya Pradesh': 'మధ్యప్రదేశ్', Manipur: 'మణిపూర్', Meghalaya: 'మేఘాలయ',
    Mizoram: 'మిజోరం', Nagaland: 'నాగాలాండ్', Odisha: 'ఒడిశా', Punjab: 'పంజాబ్', Sikkim: 'సిక్కిం', Tripura: 'త్రిపుర',
    Uttarakhand: 'ఉత్తరాఖండ్', 'West Bengal': 'పశ్చిమ బెంగాల్', Kharif: 'ఖరీఫ్', Rabi: 'రబీ', Zaid: 'జాయిద్', 'Year-round': 'ఏడాది పొడవునా', Other: 'ఇతర',
    Drip: 'డ్రిప్', Sprinkler: 'స్ప్రింక్లర్', Flood: 'నీటి ముంపు', Manual: 'చేతితో', None: 'ఏదీ లేదు',
    High: 'అధికం', Medium: 'మధ్యస్థం', Low: 'తక్కువ', Rising: 'పెరుగుతోంది', Stable: 'స్థిరం', Falling: 'తగ్గుతోంది',
  },
  ta: {
    Home: 'முகப்பு', Crops: 'பயிர்கள்', Weather: 'வானிலை', Market: 'சந்தை', Profile: 'சுயவிவரம்',
    Settings: 'அமைப்புகள்', Notifications: 'அறிவிப்புகள்', Logout: 'வெளியேறு',
    'Add Crop': 'பயிர் சேர்க்க', 'Crop Advisor': 'பயிர் ஆலோசகர்', 'Profit Calc': 'லாப கணக்கு',
    Irrigation: 'நீர்ப்பாசனம்', 'My Profile': 'என் சுயவிவரம்', 'Market & Demand': 'சந்தை மற்றும் தேவை',
    'Profit Calculator': 'லாபக் கணிப்பான்', 'Smart Irrigation': 'சிறந்த நீர்ப்பாசனம்',
    'AI Crop Advisor': 'பயிர் ஆலோசகர்', 'Add New Crop': 'புதிய பயிர் சேர்க்க',
    'Good morning 🌅': 'காலை வணக்கம் 🌅', 'Quick Actions': 'விரைவு செயல்கள்',
    'Active Crops': 'தற்போதைய பயிர்கள்', 'My Crops': 'என் பயிர்கள்', 'View All →': 'அனைத்தையும் காண்க →',
    'Live Farm Forecast': 'வயல் வானிலை முன்னறிவிப்பு',
    'Current conditions and a five-day forecast for your location': 'உங்கள் இடத்தின் தற்போதைய நிலை மற்றும் ஐந்து நாள் முன்னறிவிப்பு',
    'Find crops for your farm': 'உங்கள் வயலுக்கான பயிர்களைத் தேர்ந்தெடுக்கவும்',
    'Recommendations use your soil, water source, and growing season.': 'மண், நீர் ஆதாரம் மற்றும் பருவத்தின் அடிப்படையில் பரிந்துரைகள்.',
    'Soil type': 'மண் வகை', 'Water availability': 'நீர் கிடைக்கும் நிலை', Season: 'பருவம்',
    'Best matches': 'சிறந்த பொருத்தங்கள்', 'Soil match': 'மண்ணுக்கு ஏற்றது',
    'Check local soil suitability': 'உள்ளூர் மண்ணுக்கு ஏற்றதா எனச் சரிபார்க்கவும்',
    'Water match': 'நீருக்கு ஏற்றது', 'Plan reliable irrigation': 'நீர்ப்பாசனத்தைத் திட்டமிடுங்கள்',
    'These are general planning suggestions, not a guarantee of yield. Confirm seed choice and planting dates with your local agriculture extension office.': 'இவை பொதுவான திட்டமிடல் பரிந்துரைகள்; விளைச்சலுக்கு உத்தரவாதமில்லை. விதை மற்றும் நடவு தேதிகளை உள்ளூர் வேளாண்மை அலுவலகத்தில் உறுதிப்படுத்தவும்.',
    'Watering intervals are starting estimates based on crop stage, soil, and water availability. Check soil moisture and local conditions before watering.': 'பயிர் நிலை, மண் மற்றும் நீர் கிடைப்பை அடிப்படையாகக் கொண்ட தொடக்க மதிப்பீடுகள் இவை. நீர் பாய்ச்சும் முன் மண் ஈரப்பதத்தைச் சரிபார்க்கவும்.',
    'Watering method to log': 'பதிவு செய்யும் நீர்ப்பாசன முறை', 'Check moisture': 'ஈரப்பதத்தைச் சரிபார்க்கவும்',
    'Recently watered': 'சமீபத்தில் நீர் பாய்ச்சப்பட்டது', 'Log watering': 'நீர்ப்பாசனத்தைப் பதிவு செய்',
    'No active crops to plan for': 'திட்டமிட தற்போதைய பயிர்கள் இல்லை',
    'Add a crop to get stage-based watering guidance.': 'நிலை அடிப்படையிலான நீர்ப்பாசன ஆலோசனைக்கு பயிர் சேர்க்கவும்.',
    'Starting interval: about every ': 'தொடக்க இடைவெளி: சுமார் ', days: 'நாட்களுக்கு ஒருமுறை',
    'Last watered: ': 'கடைசியாக நீர் பாய்ச்சியது: ', 'No watering logged yet': 'இன்னும் நீர்ப்பாசனம் பதிவு செய்யப்படவில்லை',
    'City or district': 'நகரம் அல்லது மாவட்டம்', Search: 'தேடு',
    'Loading local forecast...': 'உள்ளூர் வானிலை ஏற்றப்படுகிறது...',
    '5-day forecast': '5 நாள் முன்னறிவிப்பு', Humidity: 'ஈரப்பதம்', Wind: 'காற்று',
    'Precipitation now: ': 'தற்போதைய மழைப்பொழிவு: ',
    'Forecast by Open-Meteo. Use local observations for farm decisions.': 'Open-Meteo முன்னறிவிப்பு. விவசாய முடிவுகளுக்கு உள்ளூர் நிலையை கவனிக்கவும்.',
    'Crop & Area': 'பயிர் மற்றும் நிலப்பரப்பு', 'Yield & Price': 'விளைச்சல் மற்றும் விலை',
    'Cultivation Costs (₹)': 'சாகுபடி செலவுகள் (₹)', Crop: 'பயிர்', 'Land Area': 'நிலப்பரப்பு',
    Unit: 'அலகு', 'Expected Yield per Acre (kg)': 'ஏக்கருக்கு எதிர்பார்க்கும் விளைச்சல் (கிலோ)',
    'Selling Price per kg (₹)': 'கிலோவுக்கு விற்பனை விலை (₹)', 'Calculate Profit': 'லாபத்தைக் கணக்கிடு',
    'Estimated Profit': 'மதிப்பிடப்பட்ட லாபம்', 'Total Yield': 'மொத்த விளைச்சல்', 'Expected Revenue': 'எதிர்பார்க்கும் வருமானம்',
    'Total Cost': 'மொத்த செலவு', 'All figures are': 'அனைத்து மதிப்புகளும்', estimates: 'மதிப்பீடுகள்',
    'based on your inputs. Actual profit may vary.': 'உங்கள் உள்ளீடுகளின் அடிப்படையில் கணக்கிடப்பட்டவை. உண்மையான லாபம் மாறலாம்.',
    'Select Crop': 'பயிரைத் தேர்ந்தெடுக்கவும்', 'Crop Details': 'பயிர் விவரங்கள்', 'Crop Name *': 'பயிர் பெயர் *',
    'Select a crop': 'பயிரைத் தேர்ந்தெடுக்கவும்', 'Land Area *': 'நிலப்பரப்பு *', 'Dates & Yield': 'தேதிகள் மற்றும் விளைச்சல்',
    'Planting Date *': 'நடவு தேதி *', 'Expected Harvest Date': 'எதிர்பார்க்கும் அறுவடை தேதி',
    'Expected Yield': 'எதிர்பார்க்கும் விளைச்சல்', 'Soil & Water': 'மண் மற்றும் நீர்',
    'Water Source': 'நீர் ஆதாரம்', 'Notes (Optional)': 'குறிப்புகள் (விருப்பம்)',
    '🌱 Add Crop': '🌱 பயிர் சேர்க்க',
    English: 'ஆங்கிலம்', Hindi: 'இந்தி', Telugu: 'தெலுங்கு', Tamil: 'தமிழ்',
    'Account & Location': 'கணக்கு மற்றும் இடம்', 'Personal information and farm location': 'தனிப்பட்ட தகவல் மற்றும் வயல் இருப்பிடம்',
    'Full name': 'முழுப் பெயர்', Email: 'மின்னஞ்சல்', 'Phone number': 'தொலைபேசி எண்',
    Village: 'கிராமம்', District: 'மாவட்டம்', State: 'மாநிலம்', Language: 'மொழி',
    'Choose the language used across AgroSelf.': 'AgroSelf முழுவதும் பயன்படுத்தும் மொழியைத் தேர்ந்தெடுக்கவும்.',
    'Save settings': 'அமைப்புகளைச் சேமி', 'Settings saved successfully.': 'அமைப்புகள் வெற்றிகரமாகச் சேமிக்கப்பட்டன.',
    'Could not save settings. Please try again.': 'அமைப்புகளைச் சேமிக்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'Account details': 'கணக்கு விவரங்கள்', 'Farm location': 'வயல் இருப்பிடம்',
    'Go back': 'திரும்பிச் செல்', 'Registration failed. Please try again.': 'பதிவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    'Login failed. Please try again.': 'உள்நுழைவு தோல்வியடைந்தது. மீண்டும் முயற்சிக்கவும்.',
    Dashboard: 'முகப்புப் பலகை', 'Hello, ': 'வணக்கம், ', 'Your Farm': 'உங்கள் வயல்',
    'No active crops yet': 'தற்போதைய பயிர்கள் இல்லை', 'Add your first crop to start tracking': 'கண்காணிப்பைத் தொடங்க முதல் பயிரைச் சேர்க்கவும்',
    '+ Add First Crop': '+ முதல் பயிரைச் சேர்க்கவும்', 'Today\'s Weather': 'இன்றைய வானிலை', 'Details →': 'விவரங்கள் →',
    'Expected:': 'எதிர்பார்ப்பு:', 'View →': 'காண்க →', Harvest: 'அறுவடை',
    'No data available': 'தரவு இல்லை', 'All Demand': 'அனைத்து தேவை', 'High Demand': 'அதிக தேவை',
    'Medium Demand': 'நடுத்தர தேவை', 'Low Demand': 'குறைந்த தேவை', 'Loading market data...': 'சந்தைத் தரவு ஏற்றப்படுகிறது...',
    '🌱 Seed Cost': '🌱 விதைச் செலவு', '🧪 Fertilizer Cost': '🧪 உரச் செலவு', '👷 Labour Cost': '👷 கூலி செலவு',
    '💧 Irrigation Cost': '💧 நீர்ப்பாசனச் செலவு', '🧴 Pesticide Cost': '🧴 பூச்சிக்கொல்லி செலவு', '📦 Other Costs': '📦 பிற செலவுகள்',
    'Profit Estimate': 'லாப மதிப்பீடு', 'ESTIMATED PROFIT': 'மதிப்பிடப்பட்ட லாபம்', 'per acre': 'ஏக்கருக்கு', margin: 'லாப விகிதம்',
    'Clear sky': 'தெளிவான வானம்', 'Partly cloudy': 'ஓரளவு மேகமூட்டம்', Fog: 'மூடுபனி',
    Drizzle: 'தூறல்', Rain: 'மழை', Snow: 'பனிப்பொழிவு', Thunderstorm: 'இடியுடன் மழை',
    'Conditions unavailable': 'வானிலை விவரம் இல்லை', 'Feels like': 'உணரப்படும் வெப்பம்', Updated: 'புதுப்பிக்கப்பட்டது',
    'No matching location found for': 'இந்த இடம் கிடைக்கவில்லை:',
    'Enter a city or district to get a forecast.': 'முன்னறிவிப்புக்கு நகரம் அல்லது மாவட்டத்தை உள்ளிடவும்.',
    'Location search is unavailable. Please try again.': 'இடத் தேடல் கிடைக்கவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'Weather forecast is unavailable. Please try again shortly.': 'வானிலை முன்னறிவிப்பு கிடைக்கவில்லை. சிறிது நேரம் கழித்து முயற்சிக்கவும்.',
    'Could not load weather. Check your connection and try again.': 'வானிலையை ஏற்ற முடியவில்லை. இணைய இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
    'Personal Details': 'தனிப்பட்ட விவரங்கள்', 'Farm Location': 'வயல் இருப்பிடம்', 'Land Details': 'நில விவரங்கள்',
    'Continue →': 'தொடரவும் →', '← Back': '← பின்செல்', 'Create Account': 'கணக்கை உருவாக்கு',
    'Login to AgroSelf': 'AgroSelf-இல் உள்நுழைக', 'Welcome Back 👋': 'மீண்டும் வருக 👋',
    'Login to manage your farm': 'வயலை நிர்வகிக்க உள்நுழைக', 'Email Address': 'மின்னஞ்சல் முகவரி',
    Password: 'கடவுச்சொல்', 'New farmer?': 'புதிய விவசாயியா?', 'Create New Account': 'புதிய கணக்கை உருவாக்கு',
    'Full Name *': 'முழுப் பெயர் *', 'Phone Number *': 'தொலைபேசி எண் *', 'Password *': 'கடவுச்சொல் *',
    'Village / Town': 'கிராமம் / நகரம்', 'District *': 'மாவட்டம் *', 'State *': 'மாநிலம் *',
    'Select your state': 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்',
    'Soil Type': 'மண் வகை', 'Water Availability': 'நீர் கிடைக்கும் நிலை', 'Irrigation Type': 'நீர்ப்பாசன முறை',
    'Select State': 'மாநிலத்தைத் தேர்ந்தெடுக்கவும்', 'Saving...': 'சேமிக்கப்படுகிறது...', 'You are offline': 'நீங்கள் இணையமின்றி உள்ளீர்கள்', Offline: 'ஆஃப்லைன்',
    'Save Changes': 'மாற்றங்களைச் சேமி', Cancel: 'ரத்து செய்', 'Edit Profile': 'சுயவிவரத்தைத் திருத்து',
    'Profile updated successfully!': 'சுயவிவரம் வெற்றிகரமாகப் புதுப்பிக்கப்பட்டது!', 'Update failed.': 'புதுப்பிப்பு தோல்வியடைந்தது.',
    'No notifications yet': 'அறிவிப்புகள் இல்லை', 'Clear Read': 'படித்தவற்றை நீக்கு', Loading: 'ஏற்றப்படுகிறது...',
    unread: 'படிக்காதவை', 'Failed to load notifications.': 'அறிவிப்புகளை ஏற்ற முடியவில்லை.',
    'Failed to add crop. Please try again.': 'பயிரைச் சேர்க்க முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'Please select or enter a crop name.': 'பயிரைத் தேர்ந்தெடுக்கவும் அல்லது பெயரை உள்ளிடவும்.',
    'Please enter land area.': 'நிலப்பரப்பை உள்ளிடவும்.', 'Please enter planting date.': 'நடவு தேதியை உள்ளிடவும்.',
    'Red Sandy': 'சிவப்பு மணல் மண்', 'Black Cotton': 'கரிசல் மண்', Loamy: 'வண்டல் கலந்த மண்',
    'Sandy Loam': 'மணல் வண்டல் மண்', Clay: 'களிமண்', Alluvial: 'வண்டல் மண்', Laterite: 'செம்மண்',
    Borewell: 'ஆழ்துளைக் கிணறு', Canal: 'கால்வாய்', 'Rain-fed': 'மழையைச் சார்ந்தது', River: 'ஆறு', Pond: 'குளம்', Limited: 'குறைவு',
    Planting: 'நடவு', Seedling: 'நாற்று', Vegetative: 'வளர்ச்சி நிலை', Flowering: 'பூக்கும் நிலை',
    'Fruit Development': 'காய் வளர்ச்சி',
    Chilli: 'மிளகாய்', Tomato: 'தக்காளி', Brinjal: 'கத்திரிக்காய்', Groundnut: 'நிலக்கடலை', Cotton: 'பருத்தி',
    Maize: 'மக்காச்சோளம்', Rice: 'நெல்', Wheat: 'கோதுமை', Onion: 'வெங்காயம்', Potato: 'உருளைக்கிழங்கு', Turmeric: 'மஞ்சள்',
    Sugarcane: 'கரும்பு', Sunflower: 'சூரியகாந்தி', Soybean: 'சோயா', 'Moong Dal': 'பாசிப்பருப்பு',
    Okra: 'வெண்டைக்காய்', Cucumber: 'வெள்ளரிக்காய்', Watermelon: 'தர்பூசணி', 'Bitter Gourd': 'பாகற்காய்', Coriander: 'கொத்தமல்லி',
    acres: 'ஏக்கர்', hectares: 'ஹெக்டேர்', guntas: 'குண்டா', kg: 'கிலோ', tonnes: 'டன்', quintals: 'குவிண்டால்',
    'Land & Soil': 'நிலம் மற்றும் மண்',
    'Tell us about yourself': 'உங்களைப் பற்றி கூறுங்கள்', 'Where is your farm located?': 'உங்கள் வயல் எங்கு உள்ளது?',
    'Tell us about your farmland': 'உங்கள் விவசாய நிலத்தைப் பற்றி கூறுங்கள்', 'Full Name': 'முழுப் பெயர்', 'Phone Number': 'தொலைபேசி எண்',
    'Min. 6 characters': 'குறைந்தது 6 எழுத்துகள்', 'Enter a valid 10-digit phone number.': 'சரியான 10 இலக்க தொலைபேசி எண்ணை உள்ளிடவும்.',
    'Enter a valid email address.': 'சரியான மின்னஞ்சல் முகவரியை உள்ளிடவும்.', 'Password must be at least 6 characters.': 'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.',
    'Please enter your name.': 'உங்கள் பெயரை உள்ளிடவும்.', 'Please enter your district.': 'உங்கள் மாவட்டத்தை உள்ளிடவும்.',
    'Please select your state.': 'உங்கள் மாநிலத்தைத் தேர்ந்தெடுக்கவும்.', 'Already have an account?': 'ஏற்கனவே கணக்கு உள்ளதா?',
    'Login here': 'இங்கே உள்நுழைக', 'Creating...': 'கணக்கு உருவாக்கப்படுகிறது...', 'Create Account ✓': 'கணக்கை உருவாக்கு ✓',
    'e.g. Ramesh Kumar': 'எ.கா. ரமேஷ் குமார்', 'e.g. 9876543210': 'எ.கா. 9876543210',
    'e.g. Kothapalli': 'எ.கா. கோத்தபள்ளி', 'e.g. Guntur': 'எ.கா. குண்டூர்',
    'e.g. 3': 'எ.கா. 3', 'e.g. 1500': 'எ.கா. 1500',
    'No crops added yet': 'பயிர்கள் இன்னும் சேர்க்கப்படவில்லை', 'Start by adding your first crop': 'முதல் பயிரைச் சேர்த்து தொடங்குங்கள்',
    'Harvested': 'அறுவடை செய்யப்பட்டது', 'Expected Harvest:': 'எதிர்பார்க்கும் அறுவடை:', 'Loading crops...': 'பயிர்கள் ஏற்றப்படுகின்றன...', 'Planted': 'நடவு செய்தது',
    'active crop': 'தற்போதைய பயிர்', 'active crops': 'தற்போதைய பயிர்கள்', 'Growth Stage': 'வளர்ச்சி நிலை',
    'Updating...': 'புதுப்பிக்கப்படுகிறது...', 'Advance to': 'அடுத்த நிலைக்கு:',
    'This crop has reached the Harvest stage!': 'இந்தப் பயிர் அறுவடை நிலையை அடைந்துள்ளது!',
    Watering: 'நீர்ப்பாசனம்', 'Last watered:': 'கடைசியாக நீர் பாய்ச்சியது:', 'Not recorded': 'பதிவு செய்யப்படவில்லை',
    'Log Watering': 'நீர்ப்பாசனத்தைப் பதிவு செய்', 'Crop Info': 'பயிர் விவரம்', 'Planted On': 'நடவு செய்த தேதி',
    Edit: 'திருத்து', 'days away': 'நாட்கள் உள்ளன', 'Ready to harvest!': 'அறுவடைக்குத் தயார்!',
    'Delete Crop': 'பயிரை நீக்கு', 'Are you sure you want to delete': 'நீக்க விரும்புகிறீர்களா:',
    'Yes, Delete': 'ஆம், நீக்கு', 'Date & Time': 'தேதி மற்றும் நேரம்', Method: 'முறை', Notes: 'குறிப்புகள்',
    'Optional notes...': 'விருப்பக் குறிப்புகள்...', '💧 Save': '💧 சேமி',
    Phone: 'தொலைபேசி', Contact: 'தொடர்பு', Location: 'இடம்', 'Total Area': 'மொத்தப் பரப்பளவு',
    'Failed to load market data.': 'சந்தைத் தரவை ஏற்ற முடியவில்லை.', Note: 'குறிப்பு',
    'Prices shown are indicative estimates from APMC markets. Real market data integration planned for a future phase.': 'காட்டப்படும் விலைகள் APMC சந்தைகளின் தோராயமான மதிப்பீடுகள்.',
    'Join AgroSelf': 'AgroSelf-இல் இணையுங்கள்', 'Create your free farmer account': 'இலவச விவசாயி கணக்கை உருவாக்கவும்',
    'Smart Farming for Every Farmer': 'ஒவ்வொரு விவசாயிக்கும் சிறந்த விவசாயம்', 'Email Address *': 'மின்னஞ்சல் முகவரி *',
    'ramesh@example.com': 'ramesh@example.com', 'Toggle password visibility': 'கடவுச்சொல்லைக் காட்டு அல்லது மறை',
    'Crop Name (Custom) *': 'பயிர் பெயர் (மற்றவை) *', 'Enter crop name': 'பயிர் பெயரை உள்ளிடவும்',
    'Any additional notes about this crop...': 'இந்தப் பயிரைப் பற்றிய கூடுதல் குறிப்புகள்...', 'Adding Crop...': 'பயிர் சேர்க்கப்படுகிறது...',
    'Could not save watering log. Please try again.': 'நீர்ப்பாசனத்தைப் பதிவு செய்ய முடியவில்லை. மீண்டும் முயற்சிக்கவும்.',
    'Watering logged for': 'நீர்ப்பாசனம் பதிவு செய்யப்பட்டது:', day: 'நாள்', rain: 'மழை',
    'is ready to harvest!': 'அறுவடைக்குத் தயார்!', 'harvest in': 'அறுவடைக்கு', 'more crops': 'மேலும் பயிர்கள்',
    'This is an estimate only. Market prices and actual yield may vary.': 'இது ஒரு மதிப்பீடு மட்டுமே. சந்தை விலையும் உண்மை விளைச்சலும் மாறலாம்.',
    'Rain alerts, watering reminders, and harvest notifications will appear here.': 'மழை எச்சரிக்கைகள், நீர்ப்பாசன மற்றும் அறுவடை நினைவூட்டல்கள் இங்கே தோன்றும்.',
    'Crop not found or access denied.': 'பயிர் கிடைக்கவில்லை அல்லது அணுகல் மறுக்கப்பட்டது.', 'Loading crop...': 'பயிர் ஏற்றப்படுகிறது...',
    'Expected Harvest': 'எதிர்பார்க்கும் அறுவடை',
    'Andhra Pradesh': 'ஆந்திரப் பிரதேசம்', Telangana: 'தெலங்கானா', Karnataka: 'கர்நாடகம்', Maharashtra: 'மகாராஷ்டிரம்',
    'Tamil Nadu': 'தமிழ்நாடு', Kerala: 'கேரளம்', Gujarat: 'குஜராத்', Rajasthan: 'ராஜஸ்தான்', 'Uttar Pradesh': 'உத்தரப் பிரதேசம்',
    'Arunachal Pradesh': 'அருணாச்சலப் பிரதேசம்', Assam: 'அசாம்', Bihar: 'பீகார்', Chhattisgarh: 'சத்தீஸ்கர்', Goa: 'கோவா', Haryana: 'ஹரியானா',
    'Himachal Pradesh': 'இமாச்சலப் பிரதேசம்', Jharkhand: 'ஜார்க்கண்ட்', 'Madhya Pradesh': 'மத்தியப் பிரதேசம்', Manipur: 'மணிப்பூர்', Meghalaya: 'மேகாலயா',
    Mizoram: 'மிசோரம்', Nagaland: 'நாகாலாந்து', Odisha: 'ஒடிசா', Punjab: 'பஞ்சாப்', Sikkim: 'சிக்கிம்', Tripura: 'திரிபுரா',
    Uttarakhand: 'உத்தரகாண்ட்', 'West Bengal': 'மேற்கு வங்காளம்', Kharif: 'காரிப்', Rabi: 'ரபி', Zaid: 'சாயத்', 'Year-round': 'ஆண்டு முழுவதும்', Other: 'மற்றவை',
    Drip: 'சொட்டு நீர்', Sprinkler: 'தெளிப்பு நீர்', Flood: 'வெள்ளப் பாசனம்', Manual: 'கையால்', None: 'இல்லை',
    High: 'அதிகம்', Medium: 'நடுத்தரம்', Low: 'குறைவு', Rising: 'உயர்கிறது', Stable: 'நிலையானது', Falling: 'குறைகிறது',
  },
};

const LanguageContext = createContext(null);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguageState] = useState(() => {
    const savedLanguage = localStorage.getItem('agroself_language');
    return LANGUAGES.some(({ code }) => code === savedLanguage) ? savedLanguage : 'en';
  });

  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (nextLanguage) => {
    if (!LANGUAGES.some(({ code }) => code === nextLanguage)) return;
    localStorage.setItem('agroself_language', nextLanguage);
    setLanguageState(nextLanguage);
    document.documentElement.lang = nextLanguage;
  };

  const t = useCallback((text) => translations[language]?.[text] || text, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within LanguageProvider');
  return context;
};